### ISSUE TITLE
`sveltePreprocess` was renamed to `preprocess` : Breaks use with @vitejs/app

### ISSUE THREAD

**Issue by MattBrittan** [svelte-add/postcss#21]
Due to commit 2667681ad4c8423a07a0aedbe221da9b7c99dc43 (I believe) building a basic vite app and adding postcss generates an invalid svelte configuration. I am unsure if this is due to a change in the svelte-kit template that has not been replicated in the vite template or if this issue also impacts svelte-kit apps (but assume that was most likely tested).

To replicate:

Run `npm init @vitejs/app test-app --template svelte-ts`, `cd test-app`, `npm install`, `npm run dev` (all working).
Run `npx svelte-add postcss`, `npm install`, `npm run dev`. Fails with the following error:

```
[vite-plugin-svelte] failed to load config C:\....\test-app\svelte.config.cjs
ReferenceError: preprocess is not defined
    at Object.<anonymous> (C:\....\test-app\svelte.config.cjs:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadSvelteConfig (C:\....\test-app\node_modules\@sveltejs\vite-plugin-svelte\dist\index.js:454:20)
    at resolveOptions (C:\....\test-app\node_modules\@sveltejs\vite-plugin-svelte\dist\index.js:544:24)
    at Object.configResolved (C:\....\test-app\node_modules\@sveltejs\vite-plugin-svelte\dist\index.js:633:17)
```

This error is due to `svelte.config.cjs` being incorrectly updated to:

```
const sveltePreprocess = require('svelte-preprocess')

module.exports = {
	preprocess: [
		preprocess({
			postcss: true
		}),
	],
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: sveltePreprocess()
}
```

I believe it should be (updating it to the below fixes the issue):

```
const sveltePreprocess = require('svelte-preprocess')

module.exports = {
	preprocess: [
		sveltePreprocess({
			// Consult https://github.com/sveltejs/svelte-preprocess
			// for more information about preprocessors
			postcss: true,
		})
	],
}
```

**Comment by babichjacob** [comment]
Probably should've realized this would happen... Gonna need a few days to fix this because of school, thanks!

**Comment by aislanmaia** [comment]
This is fixed?

**Comment by babichjacob** [comment]
> This is fixed?

It is not. I have finally been able to start working on it these past 2 days though (since there was a lot of work that needed to be done before that before I could solve this—setting up / investing in the infrastructure for it). This could be fixed within 5 days if I had to estimate. As of last night, I am currently experimenting with ASTs that make it impossible for this problem to arise again.

This is a precursor to fixing https://github.com/svelte-add/tailwindcss/issues/42, which make this and that the highest priority.

**Comment by babichjacob** [comment]
This has been fixed by https://github.com/svelte-add/svelte-add/commit/26bc68557d9ad725b244819204b762efaa3d7a63!

Do be aware that because of the current state of the `svelte-add` tool, you are likely to run into other issues. Please report problems you find at https://github.com/svelte-add/svelte-add/issues (checking if there are existing issues for it before making a new one), thank you!
